from __future__ import annotations

from enum import StrEnum


class DecisionAction(StrEnum):
    APPROVE = "APPROVE"
    DOWNGRADE = "DOWNGRADE"
    OBSERVE = "OBSERVE"
    BLOCK = "BLOCK"


class ReasonSeverity(StrEnum):
    INFO = "INFO"
    SOFT = "SOFT"
    HARD = "HARD"


class ReasonCode(StrEnum):
    INFO_QUALITY_LOW = "INFO_QUALITY_LOW"
    INFO_QUALITY_CRITICAL = "INFO_QUALITY_CRITICAL"
    LINEUP_UNKNOWN = "LINEUP_UNKNOWN"
    LINEUP_STALE = "LINEUP_STALE"
    MISSING_ELO_LOSS = "MISSING_ELO_LOSS"
    HIGH_CONFIDENCE_LOW_INFO = "HIGH_CONFIDENCE_LOW_INFO"
    ENVIRONMENT_UNSAFE = "ENVIRONMENT_UNSAFE"
    ODDS_MOVE_AGAINST_MODEL = "ODDS_MOVE_AGAINST_MODEL"
    LINE_MOVE_AGAINST_MODEL = "LINE_MOVE_AGAINST_MODEL"
    INJURY_CONFLICT = "INJURY_CONFLICT"
    MARKET_DIVERGENCE_SOFT = "MARKET_DIVERGENCE_SOFT"
    MARKET_DIVERGENCE_HARD = "MARKET_DIVERGENCE_HARD"
    CHAOS_RISK_ELEVATED = "CHAOS_RISK_ELEVATED"
    CHAOS_RISK_CRITICAL = "CHAOS_RISK_CRITICAL"
    CIRCUIT_BREAKER_ACTIVE = "CIRCUIT_BREAKER_ACTIVE"

